networks:
    proxy-network:
        driver: bridge
    backend-network:
        driver: bridge

volumes:
    dataBase-volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${HOST_DB_VOL_PATH}

services:
    proxy:
        build: ${PROXY_NGINX_BUILD_PATH}
        init: true
        image: proxy-img
        restart: unless-stopped
        container_name: proxy
        ports:
            - "8080:8080"
            - "8443:8443"
        networks:
            - proxy-network
        depends_on:
            - webServer
            - serverPong

    webServer:
        build: ${WEBSERVER_NGINX_BUILD_PATH}
        init: true
        image: webserver-img
        restart: unless-stopped
        container_name: webServer
        networks:
            - proxy-network
            - backend-network

    dataBase:
        build: ${DB_BUILD_PATH}
        init: true
        image: database-img
        restart: unless-stopped
        container_name: dataBase
        volumes:
            - dataBase-volume:/usr/src/app/data
        networks:
            - proxy-network #TODO proxy solo para pruebas con el host
            - backend-network

    serverPong:
        build: ${SPONG_BUILD_PATH}
        init: true
        image: serverpong-img
        restart: unless-stopped
        container_name: serverPong
        networks:
            - proxy-network #TODO proxy solo para pruebas con el host
            - backend-network
        depends_on:
            - webServer