networks:
    proxy-network:
        driver: bridge
    backend-network:
        driver: bridge

services:
    proxy:
        build: ${PROXY_NGINX_BUILD_PATH}
        init: true
        image: proxy-img
        restart: unless-stopped
        container_name: proxy
        ports:
            - "80:80"
            - "443:443"
        networks:
            - proxy-network

    webServer:
        build: ${WEBSERVER_NGINX_BUILD_PATH}
        init: true
        image: webserver-img
        restart: unless-stopped
        container_name: webServer
        networks:
            - proxy-network
            - backend-network